version: "3.9"
services:
  nestjs-typeorm:
    image: postgres
    restart: always
    container_name: nestjs-typeorm
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: example
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres

volumes:
  postgres:


